name: Bug Report
description: Report a bug in Ulauncher.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this report!**
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your Linux distro, desktop environment and other relevant information for reproducing the issue.
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: What did you do to trigger the issue? What happened, and what did you expected to happen instead?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Run Ulauncher from the shell with `ulauncher -v` and copy and paste the log output or grab the log from the previous session (`~/.local/share/ulauncher/last.log` for v5 or `~/.local/state/ulauncher/last.log` for v6). This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: communication-guidelines
    attributes:
      label: Communication guidelines
      description: Did you read the [communication guidelines](https://github.com/Ulauncher/Ulauncher/blob/HEAD/CODE_OF_CONDUCT.md) and [troubleshooting category](https://github.com/Ulauncher/Ulauncher/discussions/categories/troubleshooting)?
      options:
        - label: I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.
          required: true
        - label: I have tried to understand the error message and help myself, before reporting it.
          required: true
        - label: My issue description has clear steps for how to reproduce the issue.
          required: true
        - label: This issue applies to the whole Ulauncher application, not for a specific extension.
          required: true
  - type: checkboxes
    id: latest
    attributes:
      label: Ulauncher v6
      description: Please test in [Ulauncher v6 (beta)](https://github.com/Ulauncher/Ulauncher/issues/869) or at least read through this post to ensure the bug hasn't already been fixed. Note that Ulauncher v6 doesn't have a stable release yet.
      options:
        - label: I have made sure the bug isn't already fixed in v6.
          required: false
